name: 'Generate QR Code'
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  generate-qr-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qrcode boto3 pillow 
      
      - name: Run Python file
        env:
          QR_CODES_S3_BUCKET_NAME: ${{ secrets.QR_CODES_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python deployment_scripts/generate_qrcode.py