name: 'Generate QR Code'
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qrcode  # If you have dependencies
      
      - name: Run Python file
        run: |
          python deployment_scripts/qrcode.py